AWSTemplateFormatVersion: '2010-09-09'
Description: DynamoDB aislada (on-demand)

Resources:
  AppTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-table'

Outputs:
  AppTableName:
    Value: !Ref AppTable
    Export:
      Name: !Sub '${AWS::StackName}-AppTableName'
