service: vpc
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

resources:
  - ${file(resources.yml)}

outputs:
  VpcId: ${cf:${self:service}-${self:provider.stage}.VpcId}
  PrivateSubnet1Id: ${cf:${self:service}-${self:provider.stage}.PrivateSubnet1Id}
  PrivateSubnet2Id: ${cf:${self:service}-${self:provider.stage}.PrivateSubnet2Id}
  SecurityGroupId: ${cf:${self:service}-${self:provider.stage}.SecurityGroupId}

